version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=supersecretkey
      - MONGO_URI=mongodb://mongo:27017/auth-api
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
